//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsPermissionChanger.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULE
    {
        public int ID { get; set; }
        public string STATUS { get; set; }
        public string GROUP { get; set; }
        public string Password { get; set; }
        public string Dept { get; set; }
        public Nullable<bool> RULE1 { get; set; }
        public Nullable<bool> RULE2 { get; set; }
        public Nullable<bool> RULE3 { get; set; }
        public Nullable<bool> RULE4 { get; set; }
        public Nullable<bool> RULE5 { get; set; }
        public Nullable<bool> RULE6 { get; set; }
        public Nullable<bool> RULE7 { get; set; }
        public Nullable<bool> RULE8 { get; set; }
        public Nullable<bool> RULE9 { get; set; }
        public Nullable<bool> RULE10 { get; set; }
        public Nullable<bool> RULE11 { get; set; }
        public Nullable<bool> AUDITOR { get; set; }
        public string ID_SELECTION { get; set; }
        public string ACTIVITY_CENTER { get; set; }
        public string SERVICE_ID_FIELDS { get; set; }
        public string TECHSTATUS { get; set; }
        public string PINCODE { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ADP { get; set; }
        public string Active { get; set; }
        public string Facility { get; set; }
        public string PackButton { get; set; }
        public byte[] Rules { get; set; }
        public string Trainee { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public Nullable<bool> Purchasing { get; set; }
        public Nullable<bool> OrderEntry { get; set; }
        public Nullable<bool> Invoicing { get; set; }
        public Nullable<bool> Receiving { get; set; }
        public Nullable<bool> Sales { get; set; }
        public Nullable<bool> Shipping { get; set; }
        public Nullable<bool> Tech { get; set; }
        public Nullable<bool> Office { get; set; }
        public Nullable<bool> BusinessAnalysis { get; set; }
        public Nullable<bool> AESMed { get; set; }
        public Nullable<bool> HumanResources { get; set; }
        public Nullable<bool> Sage { get; set; }
        public Nullable<bool> ResourceBuilder { get; set; }
        public Nullable<bool> ReportsOnDemand { get; set; }
        public Nullable<bool> EatonLabels { get; set; }
        public Nullable<bool> TrimbleLabels { get; set; }
        public Nullable<bool> Quoting { get; set; }
        public string IPAddress { get; set; }
    }
}
