//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsPermissionChanger.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportsIndex
    {
        public string ReportID { get; set; }
        public string Name { get; set; }
        public string Freq { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string FileType { get; set; }
        public string Distribution { get; set; }
        public string AROD { get; set; }
        public string Active { get; set; }
        public string EmailFrom { get; set; }
    }
}
